server {
    listen 80; # Listen on port 80, if you want to use https, change it to 443
    server_name localhost; # Server name
    
    root /var/www/app/public; # Root directory, for laravel where index.php is located
    index index.php; # Index file

    client_max_body_size 10M; # Maximum file size for uploads

    # Handle storage directory access
    location /storage/ { 
        deny all; # Deny access to storage directory
    }
    
    # Handle all other requests
    location / {
        proxy_pass http://113.193.64.150:8088;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Here $uri is the requested URI, for example /about or /contact
        # $uri/ is the requested URI with a trailing slash, for example /about/ or /contact/
        # $query_string is the query string, for example ?name=John
        # Example -1 : Browser asks /css/app.css, nginx will try to find /css/app.css file, if it exists, it will be served
        # Example -2 : Browser asks /about, nginx will try to find /about file, if it doesn't exist, it will try to find /about/ directory, if it doesn't exist, it will be handled laravels router
        try_files $uri $uri/ /index.php?$query_string;

    }
    
    # Handle PHP files
    location ~ \.php$ {
        try_files $uri =404; # If file doesn't exist, return 404
        fastcgi_pass app:9000; # Pass request to PHP-FPM container
        fastcgi_index index.php; # Tells FastCGI that the default file is index.php
        include fastcgi_params; # Loads default FastCGI parameters

        # SCRIPT_FILENAME is the path to the PHP file that will be executed
        # $document_root is the root directory of the website
        # $fastcgi_script_name is the path to the requested file
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_read_timeout 300; # Nginx will wait up to 5 minutes for PHP-FPM to respond
    }

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}